### ISSUE TITLE
Sugerencia para Vale Tiznado

### ISSUE THREAD

**Issue by MartinGonzalezUAI** [montoyamoraga/dis145#102]
Hola @valetiznado, te sugiero que pongas los backticks al reves cuando escribas un codigo en tu read.me

@montoyamoraga @janisepulveda

**Comment by janisepulveda** [comment]
esos tildes al reves se llaman backticks
\```

**Comment by valetiznado** [comment]
Gracias @MartinGonzalezUAI por tu ayuda!!, arreglare los backticks 😜
