### ISSUE TITLE
Sugerencia Eli Rios 

### ISSUE THREAD

**Issue by Spidermaneberl** [montoyamoraga/dis145#103]
@eliriostoro  podrias ser mas ordenada

**Comment by Spidermaneberl** [comment]
@eliriostoro era broma

**Comment by janisepulveda** [comment]
no es chistoso

**Comment by eliriostoro** [comment]
@Spidermaneberl podrías dar soluciones, no opiniones poco constructivas.

**Comment by Spidermaneberl** [comment]
@eliriostoro ‎ ʕ•́ᴥ•̀ʔ
