### ISSUE TITLE
Comentario a MacialLeaplaza

### ISSUE THREAD

**Issue by SrYuyo** [montoyamoraga/dis145#104]
Me gusta el proyecto de @MarcialLeaplaza , ojala que no se vaya al lado oscuro....

**Comment by janisepulveda** [comment]
que es lado oscuro?

**Comment by MarcialLeaplaza** [comment]
Muy tarde @SrYuyo :)

**Comment by SrYuyo** [comment]
@janisepulveda El "lado oscuro" es un concepto ficticio en el universo de Star Wars, creado por George Lucas. Se refiere a un poder maligno y corruptor que otorga habilidades sobrenaturales a quienes lo utilizan, pero a menudo conlleva a la corrupción moral y emocional. Los usuarios del lado oscuro tienden a buscar el poder y el dominio sobre los demás, generalmente a expensas de la ética y la compasión.

Los practicantes del lado oscuro, como los Sith, utilizan sus habilidades para fines egoístas y destructivos, buscando el control absoluto y la subyugación de otros. Esto contrasta con los Jedi, que utilizan la Fuerza para promover la paz, la justicia y el equilibrio en la galaxia.

El "lado oscuro" se ha convertido en un símbolo culturalmente reconocido de la tentación hacia el mal y la corrupción en muchas narrativas de ciencia ficción y fantasía. Ha inspirado numerosas obras de ficción, así como también ha sido objeto de análisis filosóficos y psicológicos sobre la naturaleza del bien y del mal en la sociedad humana.
