### ISSUE TITLE
Problemas de representación visual

### ISSUE THREAD

**Issue by thiangie** [montoyamoraga/dis145#105]
Hola, @MarcialLeaplaza !
Para representar las ideas de tus proyectos, te podría ayudar representarlos de manera visual, ya sea con imágenes, dibujos o esquemas. Esto lograría que las personas más ajenas a los elementos que utilices pueda tener un acercamiento más ameno.

(:

@montoyamoraga @janisepulveda

**Comment by MarcialLeaplaza** [comment]
Hola. Gracias por la sugerencia, la tomare en cuenta a futuro. Si tienes dudas sobre alguna idea mía que hayas leído no dudes en preguntarme.
