### ISSUE TITLE
Sugerencia Marcial sobre informacion del proyecto

### ISSUE THREAD

**Issue by MartinGonzalezUAI** [montoyamoraga/dis145#106]
Hola @MarcialLeaplaza, seria bacan si puedes explicar mas tu proyecto en tu read.me, me tinca bueno pero con la info que sale ahi no cacho muy bien en que consiste

@montoyamoraga @janisepulveda

**Comment by MarcialLeaplaza** [comment]
Hola!
Encontré este [video](<https://www.youtube.com/watch?v=WYcriR227Dg>) que literalmente muestra lo que me gustaría hacer.
Lo pondré en mi README.md
