### ISSUE TITLE
Links en README.md

### ISSUE THREAD

**Issue by MarcialLeaplaza** [montoyamoraga/dis145#109]
Hola, @thiangie , noté que en tu README.md de la clase 07 los dos enlaces que adjuntaste al final quedaron mal, se ve que intentaste crear un link con un nombre, para ello asegúrate de que este escrito en el siguiente formato:
``[nombreLink](<link>).``
Ejemplo abajo:
[nombreLink](<link>).

@montoyamoraga @janisepulveda

**Comment by thiangie** [comment]
muchas gracias, ya lo pude solucionar :D
