### ISSUE TITLE
mejorar consistencia en nombres de archivo

### ISSUE THREAD

**Issue by montoyamoraga** [montoyamoraga/dis145#110]
ojo con nombres de archivos, que tengan un nombre seguido de un punto y una extensión.

que no tengan dos puntos para que no se confunda la extension
que estén en notación camello
que NO TENGAN ESPACIOS
ojo con esas buenas prácticas

por favor arreglar eso en clase-07 @isigoycoolea

**Comment by janisepulveda** [comment]
lo hicimos en nuestro computador
