### ISSUE TITLE
subir esto a tu README de tu clase-08 en tu fork

### ISSUE THREAD

**Issue by janisepulveda** [montoyamoraga/dis145#112]
* lista preliminar de materiales que ya tienes
* lista de materiales que tienes que conseguir
* tu proyecto explicado en 1 frase
* tu proyecto explicado en 1 párrafo
* tu proyecto explicado con 5 "hashtags", como referencia tomar los proyectos de <https://www.media.mit.edu/research/?filter=groups_centers_initiatives>

responder con un emoji aquí abajito cuando lo hayan hecho, etiquetando a todo el equipo docente

**Comment by MarcialLeaplaza** [comment]
Hay que arreglar el link de este issue.

**Comment by MartinGonzalezUAI** [comment]
👍 
@montoyamoraga  @janisepulveda

**Comment by MarcialLeaplaza** [comment]
🍴 
@montoyamoraga @janisepulveda

**Comment by SrYuyo** [comment]
🐦
@montoyamoraga @janisepulveda

**Comment by GermanGallardo** [comment]
👍

**Comment by supernave1** [comment]
😱 @montoyamoraga @janisepulveda

**Comment by thiangie** [comment]
😸  @montoyamoraga @janisepulveda

**Comment by isigoycoolea** [comment]
:last_quarter_moon: @montoyamoraga @janisepulveda

**Comment by Spidermaneberl** [comment]
🗿
@montoyamoraga @janisepulveda
