### ISSUE TITLE
SDK en un proyecto de VS2022

### ISSUE THREAD

**Issue by MarcialLeaplaza** [montoyamoraga/dis145#163]
Hola Profe y Janis, ya logré crear mi primer plugin :) El único problema es que el SDK que instalé para generar el plugin (el único disponible que encontré para VS).

Quería saber si usted conoce algún otro portal donde pueda desarrollar los componentes o si existe alguna forma de hacer que el builder use un SDK mas antiguo que sea compatible con el de mi version de grasshopper.

El error en cuestión es el siguiente:

<img width="572" alt="SDK_info" src="https://github.com/montoyamoraga/dis145/assets/165319963/b3164fa6-d850-49a8-8781-f703c526f49f">

En este caso el componente que intente instalar en grasshopper es "Workshop".

He estado buscando varia horas por intenet distintas soluciones, entre ellas pagar una subscripcion para VS2017 (al final seria un material para el proyecto...?) pero me gustara saber si existen otras opciones.

@montoyamoraga @janisepulveda

**Comment by MarcialLeaplaza** [comment]
@montoyamoraga @janisepulveda Ayuda plis :(

**Comment by MarcialLeaplaza** [comment]
Ya logré progresar. Lamentablemente no podré hacerlo en rhino 7, sin embargo, los 90 días gratis de rhino 8 deberían ser suficientes para terminar el proyecto. De todos modos, seguiré buscando alguna forma de programar los componentes con un sdk compatible con rhino 7 para poder compartirlo con gente que no tenga 200usd para gastar en rhino 8.

Puse mis avances en la clase 13, por si quieren ver más detalles.

**Comment by montoyamoraga** [comment]
súper @MarcialLeaplaza , estoy revisando tus apuntes
arreglé algunas faltas de ortografía
y estoy tramitando una licencia de rhino 8 para mí
para probar el SDK también en mi computador
y sí, te agradezco mucho el esfuerzo,
los software pueden ser carísimos y la idea
es que nuestros proyectos sean accesibles

 puedes agregar al README.ms instrucciones muy detalladas
o los enlaces o manuales que seguiste
para instalar la SDK y compilar tu plugin?
para probarlo en mi computador y ver qué puedo hacer
además así queda completa tu entrega con todo el manual

suerte!!

**Comment by MarcialLeaplaza** [comment]
Oka! @montoyamoraga gracias y perdón por el cachito del rhino 8.

Igual rhino 8 está resuelto en el mismo framework (.Net4.8) así que cuando lo instale ya debería estar listo para poder usar los plugins, Luego si llego a necesitar de alguna otra librería externa, incluiré todo en el README.md
