### ISSUE TITLE
Información faltante

### ISSUE THREAD

**Issue by pedrolegarraga1** [montoyamoraga/dis145#48]
Buenas tardes Profesor, 

hay un problema con mi foro, me hace falta un ejercicio el cual desapareció.

https://github.com/pedrolegarraga1/dis145/tree/3b42f64d1848dc162573bd8173c7437381f4e620/estudiantes/pedrolegarraga1
en este link puede ver e ejercicio del cual le hablo. (desde la primera imagen hacia abajo)

Muchas gracias
Pedro.

**Comment by montoyamoraga** [comment]
listo @pedrolegarraga1
